# Generated by Django 4.1 on 2022-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countfield', models.IntegerField(default=0, max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('tz_id', models.CharField(max_length=50)),
                ('localtime', models.DateTimeField()),
                ('lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField()),
                ('temp_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feelslike_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_dir', models.CharField(max_length=5)),
            ],
        ),
    ]
