# Generated by Django 4.1 on 2022-09-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheatherreport',
            name='countfield',
            field=models.IntegerField(default=0),
        ),
    ]
